const express = require("express");
const routes = require("./routes");
const files = require("./middlewares/files");
const error404 = require("./middlewares/404");
const path = require("path");
const app = express();
app.use(express.json());
app.use(express.static(path.join(__dirname, "/uploads/")));
app.use("/", routes);
app.use(error404);
app.listen(3000, () => console.log("Server started on port 3000"));
